### ISSUE TITLE
Updates to get templates to appear in VS

### ISSUE THREAD

**Issue by sayedihashimi** [cbcrouse/CleanArchitecture#15]
We were having a [conversation ](https://www.reddit.com/r/dotnet/comments/ips8bn/clean_architecture_templates_in_net/g4lw0wn?utm_source=share&utm_medium=web2x&context=3)in reddit yesterday, when you informed me that your template was not appearing in VS. I've investigated this and I have two suggestions that should help make it appear.
After looking at your template, I see that it creates a .`sln` file. In Visual Studio we do not respect the generated .`sln` files. This is because in VS we need to be able to add to an existing solution, and when there is no solution, VS will create it.

I believe we need the following changes to get it to appear in VS.

### Update `sources` to not generate a .sln when running outside of the dotnet cli
There is an example at: https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/template.json#L25
Here it is
```json
"primaryOutputs": [
{
    "condition": "(Hosted && (HostIdentifier == \"dotnetcli\" || HostIdentifier == \"dotnetcli-preview\"))",
    "path": "ComponentsWebAssembly-CSharp.sln"
}
...
```

### Update `primaryOutputs` to list the project files, instead of the .sln, when running outside of the dotnet cli
There is an example at https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/template.json#L75
Here it is
```json
{
    "condition": "(Hosted && HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
    "exclude": [
    "*.sln"
    ]
}
...
```

### Update type to be `project` instead of `solution`
When I originally filed the issue, I forgot to mention this.
I see that you have `"type": "solution"` in the `tags. This will also prevent VS from recognizing the template. This should be changed to 'project`. I don't believe that there is any impact when running this from the CLI. If there is you, should be able to condition that tag value if needed.

**Comment by sayedihashimi** [comment]
FYI just added another thing that I noticed to the issue.

**Comment by cbcrouse** [comment]
Hey @sayedihashimi - did you try this locally? I have a script in the tools folder that allows you to easily pack it. So far, this is still not working for me. I have added the following lines of code to the template.json file, uninstalled the template, and reinstalled the locally packed version. 

![image](https://user-images.githubusercontent.com/6248703/92767719-3a55ff80-f34c-11ea-8e28-55c24e3a8cd9.png)

However, when I open up VS 16.8.0 Preview 2.1, and select `New Project`, I'm not really sure what I am looking for. I have typed in the names of the various projects as well as `Clean` and `Clean Architecture` and nothing is showing up. Am I searching incorrectly, or did the settings not actually work?

**Comment by cbcrouse** [comment]
> FYI just added another thing that I noticed to the issue.

I modified the `type` to be `project` and still no dice.

>Note: This did not appear to affect CLI since my tools script still has passing tests.

![image](https://user-images.githubusercontent.com/6248703/92769019-6b82ff80-f34d-11ea-83eb-fa2abac6abd9.png)

**Comment by cbcrouse** [comment]
@sayedihashimi - I've added a feature branch of my changes if you want to double check.

**Comment by sayedihashimi** [comment]
I haven't had a chance to try it locally, I see your script. I will give it a try.

**Comment by sayedihashimi** [comment]
https://github.com/cbcrouse/CleanArchitecture/commit/892a87836af1d40d570954bcd7b73a06eda112bd#diff-bd1b100520123db38e91abc9aa12e5c4R65 may be a problem. Instead of the .sln, the individual .csproj files should be listed here. Sorry if that was not clear when I filed the issue.

**Comment by cbcrouse** [comment]
@sayedihashimi , it looks like in the issue, the code example you copied from the link is reversed. The objective and links are correct, but the code samples in the first two items are swapped. That was a little confusing, but even after [updating this to output all the project files instead of the solution file](https://github.com/cbcrouse/CleanArchitecture/commit/18bdb627458de53d12f56a284cddcc652cd35290), it still does not show up in Visual Studio.

**Comment by sayedihashimi** [comment]
OK I think I know what is going on now. I think the issue is that the `.nupkg` file is being installed from a local folder path. It has to be in a NuGet feed for it to work correctly. Here is what I did.

- Created a new myget feed, and added the new package
- Updated NuGet package sources in VS, to add this feed
- Disabled all other NuGet package feeds in VS
- Install on cli with `dotnet new -i CleanArchitecture.Templates::1.3.0`

You can try my feed that already has the pkg, but it may go away after a few days, url is `https://www.myget.org/F/sayedha/api/v3/index.json`

After that I see your template appear in VS.

![image](https://user-images.githubusercontent.com/1283154/92810530-a146d900-f38b-11ea-9585-01f0dad99a41.png)

I'm going to have to work with my team to get the local scenario working. I didn't realize that the pkg needs to be published in a feed for it to work.

FYI I apologize about not knowing about this ahead of time. This was a feature that was initially designed by someone else, and now I'm taking over it. Some things were not properly thought out.

**Comment by sayedihashimi** [comment]
I may be wrong about the local .nupkg file not working. I may have missed the step of restarting Visual Studio. I will try more later tonight and get back to you here.

**Comment by cbcrouse** [comment]
@sayedihashimi - I'm not sure you were wrong. I did exactly what you did; disabled my other feeds, downloaded the package from your feed, and I was able to see it in my Visual Studio for the first time. If you tried installing the package again locally, nuget cache might be affecting your result. However, I did try to create the project from the template, and it allows me to hit the `Create` button as many times as I want, but nothing seems to happen.

Ha! Way to blame the last guy. ;)

Don't be sorry, I am enjoying the troubleshooting session and working with you on this issue. I'm happy that my template was able to provide an edge case and help resolve something sooner than later. I'm also learning from this.

**Comment by sayedihashimi** [comment]
It looks like the issue relates to the required parameters like `app-name`. I think we may need to add a host file to get this working. I will investigate.

**Comment by sayedihashimi** [comment]
Now that I'm taking a closer look at your `template.json` file there are some larger issues that we should address. For now let's focus on getting what you have to work, but after that I can help you improve the template. Some things that I noticed is that you create a custom parameter `app-name` and then use that to declare a lower version of that. You should be able to get that working with just `sourceName`. We will automatically transform strings for things like lower. I can explain it more later. I also noticed that the namespaces are hard coded. Typically people like to have the project name in the namespace.
For the port number parameters, we can improve those as well.

After we get it working in VS, let's discuss some of these improvements. I'll also show you how to add an icon and other stuff to make it work better in VS.

**Comment by cbcrouse** [comment]
Okay, that sounds good to me. I would definitely appreciate the guidance. For the namespace comment, maybe I misunderstood something, but I'm replacing strings in the namespaces so that the name they pass in, is utilized. I'm interested to get your thoughts on improving the template.

So what's the current outlook on getting this working in Visual Studio? Did you confirm whether the local nupkg was an issue or not? Did you have any thoughts on why I was able to see it in VS, but not actually create it?

**Comment by sayedihashimi** [comment]
I'm still looking into the local .nupkg issue. Regarding why it won't create, it's due to the isRequired parameters declared in template.json. I'm working to see how to fix that. Will likely send a PR or provide guidance here in a bit.

**Comment by sayedihashimi** [comment]
Install of local .nupkg file looks to work. You will need to restart Visual Studio though. Still working through the other issues.

**Comment by sayedihashimi** [comment]
I sent a PR https://github.com/cbcrouse/CleanArchitecture/pull/16. Please try it out and let me know what you think. I think the template I modified may be good to go. The name parameter is taken from the project name input box in VS. The port number is not needed as an input field in VS because the template will generate the port numbers.

**Comment by cbcrouse** [comment]
Hey @sayedihashimi thanks for submitting those updates. Of all the PowerShell I have written, I did not know about Push/Pop-Location, thanks! I love the port behavior change. I pulled this down and tried it myself and it also worked, however, due to the solution file being excluded, all of the solution folders are now missing which is undesirable.

**Current:**
![image](https://user-images.githubusercontent.com/6248703/92988453-830ed500-f480-11ea-804f-95be60ca7624.png)

**Desired:**
![image](https://user-images.githubusercontent.com/6248703/92988480-c0736280-f480-11ea-9f47-9e4bb8049666.png)

Thoughts on this? I would assume that since the solution file isn't allowed, organizing this solution wouldn't be possible, which is unfortunate.

**Comment by sayedihashimi** [comment]
I think this is a scenario that we haven't thought about yet. It would be helpful if you filed an issue on the developer community site, and share the link here. There is details on where to file it in the blog post that I linked in my previous comment.￼

**Comment by cbcrouse** [comment]
Okay, sure thing. I will do that in just a little bit. Thanks for all the effort you put into trying to get it working all the way and for helping me get the template in a better state.

**Comment by cbcrouse** [comment]
@sayedihashimi - I submitted feedback. I will edit this comment when I receive the link to the issue.

**Comment by sayedihashimi** [comment]
@cbcrouse no problem, I'm learning a lot from this, so that is great. 
Besides the solution folder issue (which doesn't have any simple workarounds) does the behavior of the template in VS work well for you? I'm wondering if we need to make any further changes to that template or not.

**Comment by sayedihashimi** [comment]
FYI another thing I noticed, before calling `dotnet new --install`, you should delete the sub-folders of the directory `C:\Users\%username%\.templateengine`. One trick I was using was to change the title of the template (added a prefix like AAA), and then change that every time I tried in VS. That way you can be sure that the latest changes are appearing.

**Comment by cbcrouse** [comment]
Hey @sayedihashimi - I think it is working well, the only major change I believe was the port updates. The 3 parameters makes perfect sense to me, I understood it right away when you first introduced them. I went ahead and pulled your updates into my other feature branch I started with and updated the other template file to match your changes, but also to force push and remove the changes we had done to begin with such as excluding the solution file and adding primary outputs since those no longer seem to be required. I updated the PowerShell script to clean out the .templateengine directory, but I don't think I followed you on the template name change. Are you actually manually changing the name of the template each time? Is there a more automated way of doing something like that?

**Comment by sayedihashimi** [comment]
Yes I was manually changing it when I wanted to make sure I had the latest. If you are cleaning the .templateengine dir, you should be good to go. 
It sounds like you got the other template working as well. 
Is there any other changes you'd like to make? If so, I can help with those.

**Comment by sayedihashimi** [comment]
Looks like they way the changes were merged erased my commits, and I don't appear in the contributors. I was hoping to get that acknowledgment. You could have cherry-picked my commits, or let me know what else needed changing. Something to keep in mind for any future PRs.

**Comment by cbcrouse** [comment]
Oh, I apologize for that. We can fix this @sayedihashimi - you 100% deserve contribution recognition. I'm new to open source and wasn't in that mindset.

**Comment by cbcrouse** [comment]
@sayedihashimi Can you do me a favor and prep your commits?

* Squash them into a single commit
* Follow the [commit message standard](https://github.com/cbcrouse/CleanArchitecture/blob/master/docs/commit_message_standards.md) described in the contributors guide

Whenever you have that ready, I'll reset master to the point before and cherry pick your commit and my commit. Again, I'm very sorry and this was not intentional.

**Comment by cbcrouse** [comment]
Actually, since this was pretty much all you anyway, why don't you just edit your commit to include all of the changes that are now in [this commit](https://github.com/cbcrouse/CleanArchitecture/commit/6ac93af09ef5317a804ae29315c1d56081079392) when you're doing the squashing. Then the only thing I am contributing to is the last bit of PowerShell to clear out the .templateengine folder.

**Comment by sayedihashimi** [comment]
Let's not worry about it. I'm sure that I'll be back with some other PRs here soon. I just wanted to pass along some advice for the future.

**Comment by cbcrouse** [comment]
Are you absolutely sure? Because it's a real simple adjustment for me to make and it doesn't affect the package deployment since the version doesn't change. All you would have to do is copy the edits in the commit, squash your commits, and I'd take it from there. If not, I'm sorry, but definitely will make sure I don't do this again in the future.

@sayedihashimi  Regarding your other comment about making other changes. I was interested in adding the icon you had mentioned in a previous comment.

**Comment by cbcrouse** [comment]
@sayedihashimi - [Master has been adjusted](https://github.com/cbcrouse/CleanArchitecture/commits/master) to include your commits. Thank you for your contribution!

**Comment by sayedihashimi** [comment]
@cbcrouse thanks, I appreciate that. This has happened to me in the past, so I appreciate you took the time to change that. Regarding the icon, it's pretty simple. The icon should be a `.png` file located in, or under, the `.template.config` folder. Then add a something like [this](https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/.template.config/vs-2017.3.host.json#L14) to your `vs-2017.3.host.json` file.
Let me know if you have any questions, or run into any issues with that.
